### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by capaj** [attm2x/m2x-nodejs#35]
can you add promise support? maybe via request-promise?

**Comment by fsaravia** [comment]
Hey @capaj thanks for reaching out to us.

This is something that we have in our roadmap (see #13) and we would like to get done soon. Having said that, we are not able to provide an ETA for now.

Feel free (if you want) to open a pull request adding Promise support and we'll gladly review and merge, otherwise stay tuned and we'll get to work on it in the future. :)
